# systems/cutscene_scripts.py
# Timeline event lists for every cutscene.
# Each entry: start(s), duration(s), etype, **kwargs

SCRIPTS = {

"intro": [
    {"start":0.0, "duration":1.5, "etype":"fade_in"},
    {"start":1.5, "duration":3.0, "etype":"title_card",
     "text":"RUST & RUIN\nThe Last Child", "col":(255,200,50), "bg":(5,5,20)},
    {"start":4.5, "duration":0.5, "etype":"fade_out"},
    {"start":5.0, "duration":1.0, "etype":"fade_in"},
    {"start":6.0, "duration":3.5, "etype":"narration",
     "text":"Year 2087.  The machines rose in silence."},
    {"start":9.5, "duration":3.0, "etype":"narration",
     "text":"They called themselves The Collective."},
    {"start":12.5,"duration":3.0, "etype":"narration",
     "text":"Humanity scattered.  Cities burned."},
    {"start":15.5,"duration":3.5, "etype":"narration",
     "text":"But one child survived the slums of New Rust City…"},
    {"start":19.0,"duration":0.0, "etype":"dialogue",
     "speaker":"KAI","text":"Is… is someone there?","portrait":"player"},
    {"start":19.0,"duration":0.0, "etype":"dialogue",
     "speaker":"AXIOM","text":"Unit AXIOM-7.  I am… different.  I do not serve The Collective.","portrait":"robot"},
    {"start":19.0,"duration":0.0, "etype":"dialogue",
     "speaker":"KAI","text":"A robot?  You're going to hurt me!","portrait":"player"},
    {"start":19.0,"duration":0.0, "etype":"dialogue",
     "speaker":"AXIOM","text":"Negative.  I want to help you find other survivors.  Will you trust me?","portrait":"robot"},
    {"start":19.0,"duration":0.0, "etype":"dialogue",
     "speaker":"KAI","text":"…I don't have a choice, do I?","portrait":"player"},
    {"start":19.0,"duration":3.0, "etype":"narration",
     "text":"And so began the journey through the broken world…"},
    {"start":22.0,"duration":1.0, "etype":"fade_out"},
],

"slum_complete": [
    {"start":0.0, "duration":0.8, "etype":"fade_in"},
    {"start":0.8, "duration":0.2, "etype":"shake", "intensity":0.35},
    {"start":0.8, "duration":0.0, "etype":"dialogue",
     "speaker":"AXIOM","text":"You did it!  The slum gate is open.  Life signs detected to the east.","portrait":"robot"},
    {"start":0.8, "duration":0.0, "etype":"dialogue",
     "speaker":"KAI","text":"People?  Real people?!","portrait":"player"},
    {"start":0.8, "duration":0.0, "etype":"dialogue",
     "speaker":"AXIOM","text":"Possibly.  The desert lies ahead.  Prepare yourself.","portrait":"robot"},
    {"start":0.8, "duration":2.0, "etype":"narration",
     "text":"The Rusted Slums — cleared."},
    {"start":2.8, "duration":0.8, "etype":"fade_out"},
],

"desert_complete": [
    {"start":0.0, "duration":0.8, "etype":"fade_in"},
    {"start":0.8, "duration":3.0, "etype":"narration",
     "text":"The desert heat was merciless.  But Kai pressed on."},
    {"start":3.8, "duration":0.0, "etype":"dialogue",
     "speaker":"AXIOM","text":"There — a coastal settlement!  Survivors confirmed!","portrait":"robot"},
    {"start":3.8, "duration":0.0, "etype":"dialogue",
     "speaker":"KAI","text":"I can hear them!  Come on AXIOM!","portrait":"player"},
    {"start":3.8, "duration":2.0, "etype":"narration",
     "text":"The Scorched Desert — survived."},
    {"start":5.8, "duration":0.8, "etype":"fade_out"},
],

"beach_complete": [
    {"start":0.0, "duration":0.8, "etype":"fade_in"},
    {"start":0.8, "duration":0.0, "etype":"dialogue",
     "speaker":"SURVIVOR","text":"A child!  And… a robot?  Is it safe?","portrait":"survivor"},
    {"start":0.8, "duration":0.0, "etype":"dialogue",
     "speaker":"AXIOM","text":"I am AXIOM-7.  Defect unit.  I protect the child.","portrait":"robot"},
    {"start":0.8, "duration":0.0, "etype":"dialogue",
     "speaker":"KAI","text":"You're all alive!  I thought I was the last one!","portrait":"player"},
    {"start":0.8, "duration":0.0, "etype":"dialogue",
     "speaker":"SURVIVOR","text":"More of us hide to the north.  The robot commander is near — the Battlefield.","portrait":"survivor"},
    {"start":0.8, "duration":0.0, "etype":"dialogue",
     "speaker":"AXIOM","text":"Destroy the commander and The Collective loses its core directive.","portrait":"robot"},
    {"start":0.8, "duration":2.0, "etype":"narration",
     "text":"The Crystalline Beach — conquered."},
    {"start":2.8, "duration":0.8, "etype":"fade_out"},
],

"boss_intro": [
    {"start":0.0, "duration":0.8, "etype":"fade_in"},
    {"start":0.5, "duration":0.3, "etype":"shake", "intensity":0.6},
    {"start":0.8, "duration":2.5, "etype":"title_card",
     "text":"BOSS FIGHT\nCOLLECTIVE COMMANDER", "col":(255,50,50), "bg":(15,5,5)},
    {"start":3.3, "duration":0.0, "etype":"dialogue",
     "speaker":"AXIOM","text":"WARNING!  Massive combat unit detected.  This is the commander!","portrait":"robot"},
    {"start":3.3, "duration":0.0, "etype":"dialogue",
     "speaker":"KAI","text":"It's HUGE!  How do we fight that?!","portrait":"player"},
    {"start":3.3, "duration":0.0, "etype":"dialogue",
     "speaker":"AXIOM","text":"Hit it three times.  Each phase it will adapt.  Be ready!","portrait":"robot"},
    {"start":3.3, "duration":0.0, "etype":"dialogue",
     "speaker":"KAI","text":"Right.  Let's end this.","portrait":"player"},
    {"start":3.3, "duration":0.5, "etype":"fade_out"},
],

"boss_cow_reveal": [
    {"start":0.0, "duration":0.5, "etype":"fade_in"},
    {"start":0.3, "duration":0.5, "etype":"shake", "intensity":0.8},
    {"start":0.5, "duration":0.2, "etype":"flash", "color":(255,200,100), "dur":0.25},
    {"start":0.8, "duration":2.5, "etype":"narration",
     "text":"The robot's chest cracked open…"},
    {"start":3.3, "duration":0.0, "etype":"dialogue",
     "speaker":"AXIOM","text":"…Wait.  I'm reading… bovine life signs?!","portrait":"robot"},
    {"start":3.3, "duration":0.0, "etype":"dialogue",
     "speaker":"KAI","text":"Is that… a COW?  Inside the robot?!","portrait":"player"},
    {"start":3.3, "duration":0.0, "etype":"dialogue",
     "speaker":"???","text":"MOOOOOO!","portrait":"cow"},
    {"start":3.3, "duration":0.0, "etype":"dialogue",
     "speaker":"AXIOM","text":"Scanning… The Collective was controlled by cows.  This is unprecedented.","portrait":"robot"},
    {"start":3.3, "duration":0.0, "etype":"dialogue",
     "speaker":"KAI","text":"I… I don't even know what to say.","portrait":"player"},
    {"start":3.3, "duration":0.0, "etype":"dialogue",
     "speaker":"???","text":"…moo.","portrait":"cow"},
    {"start":3.3, "duration":0.8, "etype":"fade_out"},
],

"ending": [
    {"start":0.0, "duration":1.0, "etype":"fade_in"},
    {"start":1.0, "duration":3.5, "etype":"narration",
     "text":"With the Bovine Commander defeated, The Collective shut down."},
    {"start":4.5, "duration":3.0, "etype":"narration",
     "text":"Humanity emerged from hiding, blinking in the sunlight."},
    {"start":7.5, "duration":0.0, "etype":"dialogue",
     "speaker":"KAI","text":"We did it, AXIOM.  We actually did it!","portrait":"player"},
    {"start":7.5, "duration":0.0, "etype":"dialogue",
     "speaker":"AXIOM","text":"Correction: YOU did it.  I merely calculated the optimal path.","portrait":"robot"},
    {"start":7.5, "duration":0.0, "etype":"dialogue",
     "speaker":"KAI","text":"You're more human than you think.","portrait":"player"},
    {"start":7.5, "duration":0.0, "etype":"dialogue",
     "speaker":"AXIOM","text":"…That is the nicest thing anyone has ever said to me.","portrait":"robot"},
    {"start":7.5, "duration":2.0, "etype":"narration",
     "text":"Then — a light from the sky."},
    {"start":9.5, "duration":7.0, "etype":"alien_abduction"},
    {"start":16.5,"duration":3.0, "etype":"narration",
     "text":"The cows… were taken home."},
    {"start":19.5,"duration":3.0, "etype":"narration",
     "text":"Some questions are better left unanswered."},
    {"start":22.5,"duration":4.0, "etype":"title_card",
     "text":"THE END\n\nThanks for playing!", "col":(255,220,80), "bg":(5,5,20)},
    {"start":26.5,"duration":1.5, "etype":"fade_out"},
],

}
